- hosts: all
  become: true
  vars:
      home: /home/vagrant
      document_root: /vagrant
      os: ubuntu
      user: vagrant
      osversioncode: xenial
  gather_facts: no
  pre_tasks:
    - name: Update apt cache and optionally upgrade
      apt:
        update_cache=yes
        cache_valid_time=7200
    - name: Install stuff from Aptitude
      apt: name={{ item }} state=installed
      with_items:
        - git
        - vim
        - bash-completion
        - make
        - tree
        - htop
        - man-db
    - name: Ensure sshd can connect to new hosts in non-interactive mode
      lineinfile:
        path: /etc/ssh/ssh_config
        regexp: '^StrictHostKeyChecking'
        line: 'StrictHostKeyChecking no'
    - name: Add PK to access github
      lineinfile:
        path: /etc/ssh/ssh_config
        line: 'IdentityFile ~/.ssh/gitHubKey' 
  roles:
    - { role: golang, become: true }
  tasks:
    - file:
       state: directory
       recurse: yes
       path: "{{ go_path }}/src/github.com/spiffe"
       owner: "{{ user }}"
       group: "{{ user }}"     
    - file:
        src: /mnt/spire
        dest: "{{ go_path }}/src/github.com/spiffe/spire"
        owner: "{{ user }}"
        group: "{{ user }}"
        state: link
    - name: Build SPIRE
      make:
        chdir: "{{ go_path }}/src/github.com/spiffe/spire"
      environment:
        GOPATH: "{{ go_path }}"
        GOROOT: "{{ go_root }}"
        PATH: "{{ go_root }}/bin:/usr/bin:/bin"
      become: yes
      become_user: "{{ user }}"
    - name: Add to path
      file:
        state: link
        src: "{{ go_path }}/src/github.com/spiffe/spire/cmd/spire-server/{{ item }}"
        dest: "/usr/local/bin/{{ item }}"
      with_items:
        - 'spire-server'
        - 'spire-agent'
      become: yes
      become_user: "{{ user }}"